---
name: Antonio C. da Silva Júnior
# position: "Cientista de dados"
address: "Curitiba/PR - Brasil"
phone: +55 41 987827799
www: juniorssz.github.io/home/
email: juniorssz@gmail.com
linkedin: juniorssz
github: juniorssz
# aboutme: ""
date: "Agosto 2020"
headcolor: "333333"
output: vitae::awesomecv
lang: pt-BR
docname: "Currículo"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)

source("../scripts/install.R")
```

# Objetivo
```{r}
goal <- read_csv(here::here("data", "goal.csv"))

goal %>% 
  detailed_entries(what = goal)
```


# Habilidades
```{r}
skills <- read_csv(here::here("data", "skills.csv")) %>% 
  group_by(category) %>% 
  mutate(skill = paste(skill, collapse = ", ")) %>% 
  ungroup %>% 
  unique

skills %>% 
  detailed_entries(what = skill, with = category)
```


# Formação
```{r}
education <- read_csv(here::here("data", "education.csv"))

education %>% 
  detailed_entries( 
    when = loc,
    what = uni,
    where = end_date,
    with = degree,
    why = details)
```


# Idioma
```{r}
language <- read_csv(here::here("data", "language.csv"))

language %>% 
  detailed_entries(what = language)
```


# Últimas Experiências
```{r}
jobs <- read_csv(here::here("data", "jobs.csv"))

jobs %>% 
  detailed_entries( 
    when = loc,
    what = uni,
    where = date,
    with = degree,
    why = details)
```


# Cursos Extracurriculares
```{r}
courses <- read_csv(here::here("data", "courses.csv"))

courses %>% 
  detailed_entries(
    what = institution,
    with = course)
```